### ISSUE TITLE
Make SQLBee agnostic to Cloud SQL instance types

### ISSUE THREAD

**Issue by cbenjemaa** [connctd/sqlbee#2]
@dereulenspiegel 

Currently SQLBee support only Cloud SQL instance running MYSQL. 

https://github.com/connctd/sqlbee/blob/master/cmd/sqlbee/mutate.go#L165

**Comment by dereulenspiegel** [comment]
Cloud SQL Proxy is basically just a TCP proxy. This line specifies that Cloud SQL Proxy listens on port 3306 on localhost and forwards everything towards the specified instance. It should not matter whether this instance is MySQL oder PostgreSQL based.
However 3306 is the default MySQL port and it might be awkward to specify a psql connection to port 3306. Also there are many other reasons to make a listening port configurable. So it probably makes sense to make the listening port configurable.
But this line should not block Cloud SQL Proxy from proxying psql connections.
